### ISSUE TITLE
Audio not working properly in 0.7.0.93

### ISSUE THREAD

**Issue by davexnet** [v0lt/avlib_vdplugin#1]
Hello -
the audio in 0.7.0.93 is not working properly, selelcting aac or mp3 doesn't fill in the "Format Information" fields,
and the video contains WAV audio when saved.

**Comment by v0lt** [comment]
I didn't see any negative differences compared to the old version [VirtualDub2_44282.zip](https://sourceforge.net/projects/vdfiltermod/files/VirtualDub%20pack/version%2020/).
Please make screenshots.

**Comment by davexnet** [comment]
Here you go ...
![vdub3](https://github.com/user-attachments/assets/a5c92239-efcd-4698-a500-6a4c3b1d4bd7)
![vdub2](https://github.com/user-attachments/assets/b30389dd-69c7-4450-856b-ab809c0b7f1c)
![vdub1](https://github.com/user-attachments/assets/66ee7d84-149d-4bda-8e62-585169c3f146)

**Comment by v0lt** [comment]
Thanks. The problem is clear.
Try the test builds from here - https://disk.yandex.ru/d/R3Ob8yREy4ChvA
