### ISSUE TITLE
0.7.0.93 (и новее) собраны несовместимо с windows 7

### ISSUE THREAD

**Issue by elstaar** [v0lt/avlib_vdplugin#3]
...при загрузке сообщают про отсутствующую функцию в avlib-1.vdplugin . 0.6.1.70 работает.

**Comment by v0lt** [comment]
Покажите скриншот с ошибкой. Там иногда можно нажать подробнее, чтобы понять в каком модуле проблема.

У вас проблема не с avlib-1.vdplugin. А с тем, что официальные сборки FFmpeg, а точнне avcodec-61.dll собраны с использованием функционала, который отсутсвует в Windows 7.

Посоветую поискать **shared** сборки FFmpeg 7.0.x c поддержкой Windows 7 и поменять следующие файлы:
avcodec-61.dll
avformat-61.dll
avutil-59.dll
swresample-5.dll
swscale-8.dll

**Comment by elstaar** [comment]
![image](https://github.com/user-attachments/assets/44356574-c039-4217-a819-e4a9f313e5fc)

Так же, скачал последний релиз virtualdub 2.1, в отдельный от прошлых версий каталог, и получилось у него при загрузке ещё и

![image](https://github.com/user-attachments/assets/5fcfa133-fd3c-4b9e-aa36-21e34e00f789)

(пару дней назад скачивал тоже последний релиз, но заменял им файлы установленного раньше 44282 - этой ошибки не было)

В общем, декларируется совместимость с Windows 7, когда её нет. Технически, ffmpeg 7 всё же собирается под Windows 7 и сборки есть (как минимум, в статическом виде, пользуюсь одной такой), но shared надо поискать...

**Comment by v0lt** [comment]
Вот эти вроде работают - https://github.com/kusaanko/FFmpeg-Auto-Build/releases
Есть shared версии.

**Comment by elstaar** [comment]
да, https://github.com/kusaanko/FFmpeg-Auto-Build/releases/download/workflow-202408180543/win64_ffmpeg_gpl_master_shared_20240818.zip работает. будем тестировать дальше

**Comment by v0lt** [comment]
Упомянул про Windows 7 в [Readme.md](https://github.com/v0lt/avlib_vdplugin/blob/master/Readme.md).
